services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
    volumes:
      - ./frontend/app:/app
    working_dir: /app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go_api
    command: go run main.go
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/app_db?sslmode=disable
      - REDIS_ADDR=redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    working_dir: /app

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6389:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
